# UPENN_DSBC_Python_Challenge

I was successfully able to print the results of the PyBank to a text file, however, I could not get it to work for the PyPoll results. Instead, I received help from one of my classmates and printed the PyPoll results to a CSV file instead.

Additionally, I was unsuccessful with the git push. Please see the Error Rejection message below.

PS C:\Users\Big Sam\UPENN_DSBC_Python_Challenge> git commit -m 'This is my first command line commit'
[main 0b297bb] This is my first command line commit
 6 files changed, 369947 insertions(+)
 create mode 100644 PyBank/Analysis/PyBank_Results.txt
 create mode 100644 PyBank/Resources/budget_data.csv
 create mode 100644 PyBank/main.py
 create mode 100644 PyPoll/Analysis/PyPoll_Results.txt
 create mode 100644 PyPoll/Resources/election_data.csv
 create mode 100644 PyPoll/main.py
PS C:\Users\Big Sam\UPENN_DSBC_Python_Challenge> git push
info: please complete authentication in your browser...
To https://github.com/crainsk269/UPENN_DSBC_Python_Challenge.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/crainsk269/UPENN_DSBC_Python_Challenge.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
PS C:\Users\Big Sam\UPENN_DSBC_Python_Challenge>
